[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 5173
  framework = "vite"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Schedule ping-neon-scheduled function every 4 minutes
[functions."ping-neon-scheduled"]
  schedule = "*/4 * * * *"
